# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

        # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

        # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # appspec.yml Copy
      - name: Copy appspec
        run: cp appspec.yml ./deploy/

        # 파일 압축
      - name: Make zip file
        run: zip -r ./myjewelry-springboot-webservice.zip ./deploy

        # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 --acl private ./myjewelry-springboot-webservice.zip s3://myjewelry-springboot-build/

        # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name myjewelry-springboot-webservice \
          --deployment-group-name myjewelry-springboot-webservice-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=myjewelry-springboot-build,bundleType=zip,key=myjewelry-springboot-webservice.zip \
          --region ap-northeast-2